WIP fix(Playwright): delete message refinement
smartive-education/app-yeahyeahyeah pull request #172
Opened 2023-06-06 15:10 UTC by webrooster

2023-06-14 12:25 UTC, tomschall requested changes
Es sind noch einige expect ohne matchers. Ohne matcher macht ein expect aber wenig Sinn.

_Aus der Doku: You will rarely call expect by itself. Instead, you will use expect along with a "matcher" function to assert something about a value._

2023-06-14 12:25 UTC, tomschall commented on __e2e__/globalTeardown.ts
> +      expect(article_id, `👉 should have an article id ${article_id}`);
expect toBeWhat ?

2023-06-14 12:25 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +    expect(article_id, `👉 should have an article id ${article_id}`);
expect toBeWhat ?

2023-06-14 12:25 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +    expect(page.getByRole('article').first());
expect what ?

2023-06-14 12:25 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +    expect(
expect what ?

2023-06-14 12:25 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +        expect(
expect what ?

2023-06-14 12:25 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +        expect(page.getByRole('button', { name: /Liked/ }));
expect what ?

2023-06-14 15:12 UTC, tomschall requested changes
Fast geschafft. ;-)

2023-06-14 15:12 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +let testMessage: string;
Dieser Variable wird doch schon global deklariert. Warum hier nochmal ?

2023-06-14 15:14 UTC, webrooster commented on __e2e__/authenticated.test.tsx
>          expect(article_id, `👉 should have an article id ${article_id}`);
ToBeMyAss fehlt leider in der API! Ist mit not empty ergänzt worden.

2023-06-14 15:15 UTC, webrooster commented on __e2e__/authenticated.test.tsx
> +    expect(article_id, `👉 should have an article id ${article_id}`);
dito oben

2023-06-14 15:15 UTC, webrooster commented on __e2e__/authenticated.test.tsx
> +    expect(page.getByRole('article').first());
dito oben

2023-06-14 15:17 UTC, webrooster commented on __e2e__/authenticated.test.tsx
> +    expect(
Hab ich überarbeitet.

2023-06-14 15:18 UTC, webrooster commented on __e2e__/authenticated.test.tsx
> +        expect(
Ist überarbeitet!

2023-06-14 16:19 UTC, webrooster commented on __e2e__/authenticated.test.tsx
> +        expect(page.getByRole('button', { name: /Liked/ }));
Ist angepasst und sollte eigentlich im Code ersichtlich sein.

2023-06-14 16:19 UTC, webrooster commented on __e2e__/globalSetup.ts
> +const globalSetup = async (config: FullConfig, mount: any) => {
Mount wird nicht verwendet und ist rausgeputzt.

2023-06-15 16:08 UTC, tomschall requested changes
Hab noch ein paar Kommentare...

2023-06-15 16:08 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +    // COMMENT ARTICLE
Ist dieser Kommentar gewollt ?

2023-06-15 16:08 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +    let hasHashtag: boolean = false;
Diese und die nächste Zeile kann man in eine Zeile zusammenfassen und const verwenden.

```typescript
const hasHashtag: boolean = await page.isVisible(`text=${hashTag}`);
```

2023-06-15 16:08 UTC, tomschall commented on __e2e__/authenticated.test.tsx
> +    let articleIsPresent: boolean = false;
Diese Zeile kann man mit Zeile 109 zusammenfassen und const verwenden.

```typescript
const articleIsPresent: boolean = await page.isVisible(`text=${testMessage}`);
```

2023-06-16 07:06 UTC, tomschall approved these changes

2023-06-16 07:07 UTC, merged