feat(Mumble): elapsed time in mumble
smartive-education/app-yeahyeahyeah pull request #28
Opened 2023-03-09 13:35 UTC by webrooster

- Converts elapsed time till Date() now.

2023-03-09 13:48 UTC, tomschall requested changes

2023-03-09 13:48 UTC, tomschall commented on lib/timeConverter.ts
> +export const ElapsedTime = (postDate: number) => {
Das ist eine normale Funktion, keine Komponente, sollte also mit kleinem Buchstaben anfangen.

2023-03-09 13:48 UTC, tomschall commented on src/components/mumble/MumblePost.tsx
> +            <IconLink label={ElapsedTime(createdTimestamp)} type="timestamp" color="slate" onClick={handleClickTimestamp} />
Super dann sehen wir endlich eine lesbare Zeit.

2023-03-09 13:51 UTC, webrooster commented on lib/timeConverter.ts
> +export const ElapsedTime = (postDate: number) => {
Funktion nun in "camel case"

2023-03-09 13:57 UTC, tomschall commented
Super ein neues Feature

2023-03-09 13:58 UTC, tomschall approved these changes

2023-03-09 13:58 UTC, merged

2023-06-06 10:20 UTC, tomschall commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/smartive-education/app-yeahyeahyeah/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: